### ISSUE TITLE
Naming/Organizing correctly your entities

### ISSUE THREAD

**Issue by gabrielguim** [thaynnara007/ArtForAll-Backend#2]
Hi, Thaynnara

Your project is going well, I just have some advice for you.
Reviewing your project, I saw that your entities have names/behaviors that shouldn't have.

Advice:
**Router** or **Controller** in the most cases have the same name and make the same job. They are the "API entry entity", so they will call the Service to do this business logic's stuff and get what the service returns and return to the client.

**Service**, in general, has the responsibility to do all the business logic, filtering, and database queries.

**Model** or **Schema** in mongoose are the same things, they both represent an entity in your database/document that has some attributes, functions... But they can't make database queries, just receives the information and represents in a defined format.

**Comment by thaynnara007** [comment]
Ok, I guess it's done. Thank your for your advice :)
